[package]
name = "syn"
version = "0.11.11" # don't forget to update version in readme for breaking changes
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Nom parser for Rust source code"
repository = "https://github.com/dtolnay/syn"
documentation = "https://dtolnay.github.io/syn/syn/"
categories = ["development-tools::procedural-macro-helpers"]
include = ["/Cargo.toml", "/src/**/*.rs", "/README.md", "/LICENSE-APACHE", "/LICENSE-MIT"]
publish = false # this branch contains breaking changes

[[example]]
name = "dump-ast"
path = "examples/dump-ast.rs"
required-features = ["extra-traits", "parsing", "printing", "full"]

[features]
default = ["parsing", "printing", "clone-impls"]
full = []
parsing = ["quote", "synom/parsing"]
printing = ["quote", "synom/printing"]
visit = []
visit_mut = []
fold = []
clone-impls = ["synom/clone-impls"]
extra-traits = ["synom/extra-traits"]

[dependencies]
quote = { git = 'https://github.com/dtolnay/quote', optional = true }
proc-macro2 = "0.1"
unicode-xid = "0.1"
synom = { version = "0.11", path = "synom" }
nom = { version = "4.0.0-alpha1", git = "https://github.com/Geal/nom.git" }

[dev-dependencies]
rayon = "0.9"
walkdir = "1.0.1"
